changesetIgnorePatterns:
  - "**/test/**"
  - "**/eslint.config.js"
  - "**/jest.config.js"
  - "**/.clang-format"
  - "**/.prettierignore"

initScope: "@solarwinds-apm"
initFields:
  license: Apache-2.0
  publishConfig:
    provenance: true

enableGlobalCache: false
npmPublishAccess: public
preferDeferredVersions: true
preferInteractive: true
pnpFallbackMode: none

packageExtensions:
  "eslint-config-next@^13":
    peerDependencies:
      "next": ^13
