changesetIgnorePatterns:
  - "**/test/**"
  - "**/eslint.config.js"
  - "**/jest.config.js"
  - "**/.clang-format"
  - "**/.prettierignore"

initScope: "@solarwinds-apm"
initFields:
  license: Apache-2.0
  publishConfig:
    provenance: true

enableGlobalCache: false
npmPublishAccess: public
preferDeferredVersions: true
preferInteractive: true

packageExtensions:
  "@opentelemetry/instrumentation-mysql2@^0.34.0":
    dependencies:
      "@opentelemetry/sql-common": ^0.40.0
  "eslint-config-next@^13":
    dependencies:
      "next": ^13
