changesetIgnorePatterns:
  - "**/test/**"
  - "**/eslint.config.js"
  - "**/jest.config.js"
  - "**/.clang-format"
  - "**/.eslintignore"
  - "**/.prettierignore"

initScope: "@solarwinds-apm"
initFields:
  license: Apache-2.0
  publishConfig:
    provenance: true

enableGlobalCache: false
npmPublishAccess: public
preferDeferredVersions: true
preferInteractive: true
