version: "3"
services:
  16-alpine:
    build:
      context: .
      dockerfile: 16-alpine3.12.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector
  16-amazonlinux:
    build:
      context: .
      dockerfile: 16-amazonlinux2.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector
  16-debian:
    build:
      context: .
      dockerfile: 16-debian10.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector
  16-ubi:
    build:
      context: .
      dockerfile: 16-ubi8.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector
  16-ubuntu:
    build:
      context: .
      dockerfile: 16-ubuntu18.04.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector

  18-alpine:
    build:
      context: .
      dockerfile: 18-alpine.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector
  18-debian:
    build:
      context: .
      dockerfile: 18-debian.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector
  18-ubi:
    build:
      context: .
      dockerfile: 18-ubi.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector
  18-ubuntu:
    build:
      context: .
      dockerfile: 18-ubuntu.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector

  20-alpine:
    build:
      context: .
      dockerfile: 20-alpine.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector
  20-debian:
    build:
      context: .
      dockerfile: 20-debian.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector
  20-ubi:
    build:
      context: .
      dockerfile: 20-ubi.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector
  20-ubuntu:
    build:
      context: .
      dockerfile: 20-ubuntu.Dockerfile
    volumes:
      - ..:/swotel
    links:
      - apm-collector
      - otel-collector

  apm-collector:
    image: ${TEST_COLLECTOR_IMAGE:-ghcr.io/librato/apm-agent-test-collector:v2.0.0}
    volumes:
      - ..:/swotel
    expose:
      - 12224
    environment:
      PROGRAM_ARGS: /swotel/docker/apm-collector/config.json
    depends_on:
      - udpdump
  udpdump:
    build:
      context: .
      dockerfile: 18-alpine.Dockerfile
    command: [yarn node /swotel/scripts/udpdump.js]
    volumes:
      - ..:/swotel
    expose:
      - 12225

  otel-collector:
    image: ${OTEL_COLLECTOR_IMAGE:-otel/opentelemetry-collector-contrib:0.78.0}
    command: [--config=/swotel/docker/otel-collector/config.yml]
    volumes:
      - ..:/swotel
    expose:
      - 4317
