name: Dependencies
on:
  schedule:
    - cron: "0 12 * * 1" # Every Monday at 12:00 UTC
  workflow_dispatch:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable

      - run: yarn install
      - run: yarn up -R '**'
      - run: yarn dedupe

        # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
      - name: PR
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git add yarn.lock
          git checkout -b actions/lockfile
          git commit -m "Update lockfile"
          git push origin +actions/lockfile

          gh pr create -B ${{ github.ref_name }} -t "Update lockfile" --body-file .github/resources/lockfile-pr-body.md
          gh workflow run checks.yml -r actions/lockfile
        env:
          GITHUB_TOKEN: ${{ github.token }}
