name: Images
on:
  push:
    branches:
      - main
    paths:
      - "docker/alpine.Dockerfile"
      - "docker/centos.Dockerfile"
      - "docker/debian.Dockerfile"
      - ".github/workflows/images.yml"
  workflow_dispatch:
jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - alpine
          - centos
          - debian
        include:
          - image: alpine
            platforms: linux/amd64,linux/arm64
          - image: centos
            platforms: linux/amd64
          - image: debian
            platforms: linux/amd64,linux/arm64
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: docker
          file: docker/${{ matrix.image }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ghcr.io/${{ github.repository }}/dev:${{ matrix.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
