name: Release
on:
  - workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable

      - run: yarn install --immutable
      - run: yarn publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
