name: Testing Packages
on:
  - workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: "false"
      YARN_NPM_AUTH_TOKEN: ${{ github.token }}
      YARN_NPM_PUBLISH_REGISTRY: https://npm.pkg.github.com

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable

      - uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-
      - uses: actions/cache@v3
        with:
          path: |
            ~/.zig-build
            ~/.cache/zig
          key: zig-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            zig-

      - run: |
          git grep -lz '@solarwinds-apm/' | xargs -0 sed -ie 's:@solarwinds-apm/:@${{ github.repository_owner }}/solarwinds-apm-:g'
          git grep -lz -G 'solarwinds-apm[^-]' | xargs -0 sed -rie 's:solarwinds-apm([^-]):@${{ github.repository_owner }}/solarwinds-apm\1:g'
          rm yarn.lock
          yarn install
          yarn lint:fix

      - run: yarn version:testing
      - run: yarn publish
